### PR TITLE
Whoo, Markdown

### PR DESCRIPTION
**Pull request by GalaxyBalaxy**
I saw that it was on your wishlist, and it seemed something I could manage, so I did. Lets ya pick between BBCode or Markdown, with you able to set yourself a default. Fixed inputs adding BBCode's url format. Is it a perfect fix? Probably not. Does it work? Yes.

### CODE REVIEW

**Comment by GalaxyBalaxy** [comment]
Whelp I fucked up, I did not mean for FNP.json to show up. Definitely noob mistake. Time to go reset API tokens!

**Comment by OriCat101** [comment]
cool, imma try this out and merge it if it works.

**Comment by GalaxyBalaxy** [comment]
Command line support while maintaining the original script!

**Comment by GalaxyBalaxy** [comment]
There is probably some way to break this, but my testing worked from either CLI args or default

**Comment by OriCat101** [comment]
from the looks of it this seems good, couldn't test it (yet) so I'll wait for that and then merge

**Comment by GalaxyBalaxy** [comment]
There's a bug with the torrent check, I'll go fixing that

**Comment by GalaxyBalaxy** [comment]
Also spectrogram

**Comment by GalaxyBalaxy** [comment]
I'm going to close this until I fix some more bugs

**Comment by GalaxyBalaxy** [comment]
And there we go, I goofed on the order of some things

**Comment by OriCat101** [comment]
Okay I tested it and it seems to work fine except one thing, although I'm guessing that this is just user error.

So I can get the arguments to work when I do:
```bash
python main.py -p "\Various Artists - Recursive Patterns (2021) [WEB - FLAC]" -s -t "\Various Artists - Recursive Patterns (2021) [WEB - FLAC]" -c "conf" -f "bbcode"
```
aka specify a path in the argument `t` and if I leave it empty it errors out with
```bash
usage: main.py [-h] [-p PATHS [PATHS ...]] [-s] [-g] [-t SAVE_TORRENT] [-c CONFIG] [-f {bbcode,markdown}]
main.py: error: unrecognized arguments: true
```
even if I specify them like this though, no torrent gets created

Other than that it's amazing, thx for you awesome work <3

**Comment by OriCat101** [comment]
What I meant by multifolder support was support for nested albums, zb. `Lol\CD2\lol.flac` but ill just put that on the list as a separate point since your interpretation is quite useful

**Comment by GalaxyBalaxy** [comment]
I'll try to get -t to default to the album savepath

**Comment by GalaxyBalaxy** [comment]
And there we go, that seems to be fixing the issues
Running `-g` by itself will place the .torrent files in the album folders, for each respective album (yay) so Album1.torrent will go in Album1, and Album2.torrent will go in Album2. Using `-t` "C:Your/Path/Here/" will place *all* torrent files in that directory. `-t` acts as the directory pointer; it's not needed for default creation. 

I've also added some comments for the sake of readability and reminders/to-dos.

**Comment by GalaxyBalaxy** [comment]
Here we go, this should cover your nested folder desire. It will automatically put all nested folders into the .torrent file. Also changed out the progress bar, but you can very easily keep the tqdm, just undo my changes edit the pipfile/pipfile.lock

**Comment by OriCat101** [comment]
cool, I'll test it when I convince myself to move my ass out of my bed. ✨️
And I love to comment about the devide by 0 warning since I also couldn't fix it

**Comment by GalaxyBalaxy** [comment]
One day, one day we'll figure it out

**Review by OriCat101 — APPROVED** [review]
looks good thx

**Pull request merged**
